"""initial schema

Revision ID: 562edd0d5f2b
Revises: 
Create Date: 2026-02-18 12:24:32.055189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562edd0d5f2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('account_action_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('account_action_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_action_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_action_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_action_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_account_action_tokens_used_at'), ['used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_action_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_category_user_name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_categories_user_id'), ['user_id'], unique=False)

    op.create_table('ingested_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=64), nullable=False),
    sa.Column('msg_guid', sa.String(length=128), nullable=True),
    sa.Column('msg_rowid', sa.Integer(), nullable=True),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('uts', sa.Integer(), nullable=True),
    sa.Column('is_expense', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'msg_guid', name='uq_ingested_user_guid')
    )
    with op.batch_alter_table('ingested_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingested_messages_msg_guid'), ['msg_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingested_messages_msg_rowid'), ['msg_rowid'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingested_messages_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingested_messages_user_id'), ['user_id'], unique=False)

    op.create_table('memorized_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('canonical', sa.String(length=255), nullable=False),
    sa.Column('norm', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('merchant', sa.String(length=128), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'norm', name='uq_memorized_user_norm')
    )
    with op.batch_alter_table('memorized_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memorized_transactions_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_memorized_transactions_norm'), ['norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_memorized_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_merchant_user_name')
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_merchants_user_id'), ['user_id'], unique=False)

    op.create_table('security_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monthly_income_kd', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('payday_day', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount_kd', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'month', 'category_id', name='uq_budget_user_month_category')
    )
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('name_key', sa.String(length=255), nullable=False),
    sa.Column('amount_kd', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'name_key', 'amount_kd', name='uq_txn_user_triplet')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_name_key'), ['name_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount_kd', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_items_category_id'))

    op.drop_table('items')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_name_key'))
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_month'))
        batch_op.drop_index(batch_op.f('ix_budgets_category_id'))

    op.drop_table('budgets')
    op.drop_table('user_profiles')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_created_at'))

    op.drop_table('security_events')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_user_id'))
        batch_op.drop_index(batch_op.f('ix_merchants_name'))

    op.drop_table('merchants')
    with op.batch_alter_table('memorized_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memorized_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_memorized_transactions_norm'))
        batch_op.drop_index(batch_op.f('ix_memorized_transactions_last_seen'))

    op.drop_table('memorized_transactions')
    with op.batch_alter_table('ingested_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingested_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_ingested_messages_sender'))
        batch_op.drop_index(batch_op.f('ix_ingested_messages_msg_rowid'))
        batch_op.drop_index(batch_op.f('ix_ingested_messages_msg_guid'))

    op.drop_table('ingested_messages')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_user_id'))
        batch_op.drop_index(batch_op.f('ix_categories_name'))

    op.drop_table('categories')
    with op.batch_alter_table('account_action_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_action_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_account_action_tokens_used_at'))
        batch_op.drop_index(batch_op.f('ix_account_action_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_account_action_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_account_action_tokens_expires_at'))

    op.drop_table('account_action_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
