"""add_is_income_to_categories_and_budget_index

Revision ID: c6c888325571
Revises: f3a9b1d2c4e5
Create Date: 2026-02-21 20:50:51.740754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6c888325571'
down_revision = 'f3a9b1d2c4e5'
branch_labels = None
depends_on = None


def _table_exists(conn, table_name: str) -> bool:
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()


def _column_exists(conn, table_name: str, column_name: str) -> bool:
    if not _table_exists(conn, table_name):
        return False
    inspector = sa.inspect(conn)
    return any(col.get("name") == column_name for col in inspector.get_columns(table_name))


def _index_exists(conn, table_name: str, index_name: str) -> bool:
    if not _table_exists(conn, table_name):
        return False
    inspector = sa.inspect(conn)
    return any(idx.get("name") == index_name for idx in inspector.get_indexes(table_name))


def upgrade():
    conn = op.get_bind()
    legacy_tables = ("rate_limit_buckets", "budgets_old", "transactions_old", "description_memory")
    has_legacy_tables = any(_table_exists(conn, name) for name in legacy_tables)

    # Fresh schema path (normal for clean Postgres): apply only required changes.
    # Older table/index names in the autogenerated migration do not exist here.
    if not has_legacy_tables:
        if not _column_exists(conn, 'categories', 'is_income'):
            op.add_column('categories', sa.Column('is_income', sa.Boolean(), nullable=True))
        if not _index_exists(conn, 'budgets', 'ix_budgets_user_month'):
            op.create_index('ix_budgets_user_month', 'budgets', ['user_id', 'month'], unique=False)
        return

    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists(conn, 'rate_limit_buckets'):
        op.drop_table('rate_limit_buckets')
    if _table_exists(conn, 'budgets_old'):
        op.drop_table('budgets_old')
    if _table_exists(conn, 'transactions_old'):
        op.drop_table('transactions_old')
    if _table_exists(conn, 'description_memory'):
        op.drop_table('description_memory')
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_budgets_v2_month'))
        batch_op.drop_index(batch_op.f('uq_budget_user_month_category'))
        batch_op.create_unique_constraint('uq_budget_user_month_category', ['user_id', 'month', 'category_id'])
        batch_op.create_index(batch_op.f('ix_budgets_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_month'), ['month'], unique=False)
        batch_op.create_index('ix_budgets_user_month', ['user_id', 'month'], unique=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_income', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_categories_name_search'))
        batch_op.drop_index(batch_op.f('uq_categories_global_name_nocase'), sqlite_where=sa.text('user_id IS NULL'))
        batch_op.drop_index(batch_op.f('uq_category_user_name_nocase'), sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('uq_category_user_name'))
        batch_op.create_unique_constraint('uq_category_user_name', ['user_id', 'name'])

    with op.batch_alter_table('ingested_messages', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('msg_guid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('text_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('raw_text',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_ingested_messages_text_hash'))
        batch_op.drop_index(batch_op.f('ix_ingested_msg_guid'))
        batch_op.drop_index(batch_op.f('ix_ingested_msg_rowid'))
        batch_op.drop_index(batch_op.f('ix_ingested_sender_rowid_when_no_guid'), sqlite_where=sa.text('msg_guid IS NULL AND msg_rowid IS NOT NULL'))
        batch_op.drop_index(batch_op.f('uq_ingested_user_guid'), sqlite_where=sa.text('msg_guid IS NOT NULL'))
        batch_op.create_unique_constraint('uq_ingested_user_guid', ['user_id', 'msg_guid'])
        batch_op.create_index(batch_op.f('ix_ingested_messages_msg_guid'), ['msg_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingested_messages_msg_rowid'), ['msg_rowid'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('memorized_transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index(batch_op.f('uq_memorized_user_norm'))
        batch_op.create_unique_constraint('uq_memorized_user_norm', ['user_id', 'norm'])

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_merchant_user_name_nocase'), sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.drop_index(batch_op.f('uq_merchants_global_name_nocase'), sqlite_where=sa.text('user_id IS NULL'))
        batch_op.drop_index(batch_op.f('uq_merchant_user_name'))
        batch_op.create_unique_constraint('uq_merchant_user_name', ['user_id', 'name'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_transactions_date_name'))
        batch_op.drop_index(batch_op.f('idx_transactions_name_search'))
        batch_op.drop_index(batch_op.f('ix_transactions_v2_category_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_v2_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_v2_name_key'))
        batch_op.drop_index(batch_op.f('uq_txn_user_triplet'))
        batch_op.create_unique_constraint('uq_txn_user_triplet', ['user_id', 'date', 'name_key', 'amount_kd'])
        batch_op.create_index(batch_op.f('ix_transactions_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_name_key'), ['name_key'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_name_key'))
        batch_op.drop_index(batch_op.f('ix_transactions_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_category_id'))
        batch_op.drop_constraint('uq_txn_user_triplet', type_='unique')
        batch_op.create_index(batch_op.f('uq_txn_user_triplet'), ['user_id', 'date', 'name_key', 'amount_kd'], unique=1)
        batch_op.create_index(batch_op.f('ix_transactions_v2_name_key'), ['name_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_v2_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_v2_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_name_search'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_transactions_date_name'), ['date', 'name'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_merchant_user_name', type_='unique')
        batch_op.create_index(batch_op.f('uq_merchant_user_name'), ['user_id', 'name'], unique=1)
        batch_op.create_index(batch_op.f('uq_merchants_global_name_nocase'), ['name'], unique=1, sqlite_where=sa.text('user_id IS NULL'))
        batch_op.create_index(batch_op.f('uq_merchant_user_name_nocase'), ['user_id', 'name'], unique=1, sqlite_where=sa.text('user_id IS NOT NULL'))

    with op.batch_alter_table('memorized_transactions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_memorized_user_norm', type_='unique')
        batch_op.create_index(batch_op.f('uq_memorized_user_norm'), ['user_id', 'norm'], unique=1)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('ingested_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingested_messages_msg_rowid'))
        batch_op.drop_index(batch_op.f('ix_ingested_messages_msg_guid'))
        batch_op.drop_constraint('uq_ingested_user_guid', type_='unique')
        batch_op.create_index(batch_op.f('uq_ingested_user_guid'), ['user_id', 'msg_guid'], unique=1, sqlite_where=sa.text('msg_guid IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_ingested_sender_rowid_when_no_guid'), ['sender', 'msg_rowid'], unique=False, sqlite_where=sa.text('msg_guid IS NULL AND msg_rowid IS NOT NULL'))
        batch_op.create_index(batch_op.f('ix_ingested_msg_rowid'), ['msg_rowid'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingested_msg_guid'), ['msg_guid'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingested_messages_text_hash'), ['text_hash'], unique=False)
        batch_op.alter_column('raw_text',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('text_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('msg_guid',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_user_name', type_='unique')
        batch_op.create_index(batch_op.f('uq_category_user_name'), ['user_id', 'name'], unique=1)
        batch_op.create_index(batch_op.f('uq_category_user_name_nocase'), ['user_id', 'name'], unique=1, sqlite_where=sa.text('user_id IS NOT NULL'))
        batch_op.create_index(batch_op.f('uq_categories_global_name_nocase'), ['name'], unique=1, sqlite_where=sa.text('user_id IS NULL'))
        batch_op.create_index(batch_op.f('idx_categories_name_search'), ['name'], unique=False)
        batch_op.drop_column('is_income')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('ix_budgets_user_month')
        batch_op.drop_index(batch_op.f('ix_budgets_month'))
        batch_op.drop_index(batch_op.f('ix_budgets_category_id'))
        batch_op.drop_constraint('uq_budget_user_month_category', type_='unique')
        batch_op.create_index(batch_op.f('uq_budget_user_month_category'), ['user_id', 'month', 'category_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_budgets_v2_month'), ['month'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('description_memory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('canonical', sa.VARCHAR(length=255), nullable=False),
    sa.Column('norm', sa.VARCHAR(length=255), nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=False),
    sa.Column('last_seen', sa.DATETIME(), nullable=False),
    sa.Column('merchant', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('description_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_description_memory_norm'), ['norm'], unique=1)
        batch_op.create_index(batch_op.f('ix_description_memory_last_seen'), ['last_seen'], unique=False)

    op.create_table('transactions_old',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('amount_kd', sa.NUMERIC(precision=10, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions_old', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_txn_date_amt_name'), ['date', 'amount_kd', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)

    op.create_table('budgets_old',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.VARCHAR(length=7), nullable=False),
    sa.Column('category', sa.VARCHAR(length=64), nullable=False),
    sa.Column('amount_kd', sa.NUMERIC(precision=10, scale=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', 'category', name=op.f('uq_budget_month_category'))
    )
    with op.batch_alter_table('budgets_old', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budgets_month'), ['month'], unique=False)

    op.create_table('rate_limit_buckets',
    sa.Column('bucket_key', sa.TEXT(), nullable=False),
    sa.Column('window_seconds', sa.INTEGER(), nullable=False),
    sa.Column('window_bucket', sa.INTEGER(), nullable=False),
    sa.Column('count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_ts', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('bucket_key', 'window_seconds', 'window_bucket')
    )
    # ### end Alembic commands ###
