/* eslint-disable @typescript-eslint/no-unused-vars */
// GENERATED by `pnpm --filter statera-frontend run money-shape:generate` — DO NOT EDIT.
//
// One compile-time assertion per money/decimal field captured at runtime by
// apps/api/src/contract/money-wire-shape.json (B4-1, Option Y: every wire type is
// `typeof` on a real serializer's output, never transcribed). The frontend
// `tsc --noEmit` gate checks this file, so a frontend type that disagrees with the
// captured wire is a build error. Regenerate after any wire change and commit the
// result; Guard 2 in money-wire-shape.assert.test.ts fails if you do not.
//
// WHY THE WIRE TYPES ARE BAKED IN AS LITERALS, AND NOT IMPORTED (B4-2-R6).
// `resolveJsonModule` is deliberately absent from apps/web/tsconfig.json, but that
// is not the only reason: TypeScript widens a JSON import's string values to
// `string`, NOT to the literal `"string"`, so an assertion driven off an imported
// JSON compares `string` to `string` and passes for every field forever. This was
// proven empirically by a consumed `@ts-expect-error`. If you enable
// `resolveJsonModule` and "simplify" this generator to import the JSON directly,
// you will silently reintroduce that failure.
//
// WHAT THIS DOES NOT CHECK: NULLABILITY (B4-2-R2). Each leaf is compared after
// `Exclude<…, null | undefined>`, so a frontend type that wrongly omits `| null`
// still passes. That is not a regression — nullability was never in the capture's
// scope, because B4-1's NULL fail-loud guard forbids recording a null money field.
// REVISIT TRIGGER, WITH ITS COST: extending the capture to record nullability
// requires RELAXING that NULL guard, which is a blocking-clause change under TB-R13
// and therefore its own chartered cycle — not a small improvement to make in passing.
//
// R8's assertions look redundant with R4's and R9's and are NOT (B4-2-R3).
// `DashboardBundleResponse` composes `SafeToSpendResponse` and
// `AccountOverviewResponse` by reference, so e.g.
// `DashboardBundleResponse["safe_to_spend"]["monthly_income_kd"]` and
// `SafeToSpendResponse["monthly_income_kd"]` are different expressions that resolve
// through the composition. Keeping both is a free check that the bundle really is
// typed by those interfaces rather than by a divergent inline shape. Do not
// "optimise" them away. (R3-tier2 DOES merge into R3 — same endpoint, same type,
// identical captured money paths — and the generator throws if the two tiers ever
// disagree.)

import type {
  AccountOverviewResponse,
  BudgetMetricsResponse,
  DashboardBundleResponse,
  DashboardMetricsResponse,
  ExpenseBreakdownResponse,
  ExpenseMerchantTrendResponse,
  IncomePatternResponse,
  RecurringPatternsResponse,
  SafeToSpendResponse,
  SnapshotResponse,
  SpendByCategory,
  SpendByMonth,
  WeeklyDigestResponse,
} from "../types/api"

type AssertEqual<A, B> = [A] extends [B] ? ([B] extends [A] ? true : { ERR: "differ" }) : { ERR: "differ" }

// R1
const _a0: AssertEqual<Exclude<NonNullable<SpendByCategory>[string], null | undefined>, number> = true
// R2
const _a1: AssertEqual<Exclude<NonNullable<SpendByMonth>["total_kd"], null | undefined>, number> = true
// R3, R3-tier2
const _a2: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<DashboardMetricsResponse>["expense_by_category"]>[string]>[string], null | undefined>, string> = true
// R3, R3-tier2
const _a3: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<DashboardMetricsResponse>["monthly"]>[number]>["expense_kd"], null | undefined>, string> = true
// R3, R3-tier2
const _a4: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<DashboardMetricsResponse>["monthly"]>[number]>["income_kd"], null | undefined>, string> = true
// R4
const _a5: AssertEqual<Exclude<NonNullable<NonNullable<AccountOverviewResponse>["manual_entry_summary"]>["spend_mtd"], null | undefined>, string> = true
// R4
const _a6: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<AccountOverviewResponse>["month_trend"]>[number]>["income"], null | undefined>, string> = true
// R4
const _a7: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<AccountOverviewResponse>["month_trend"]>[number]>["spend"], null | undefined>, string> = true
// R4
const _a8: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<AccountOverviewResponse>["top_categories"]>[number]>["amount_kd"], null | undefined>, string> = true
// R4
const _a9: AssertEqual<Exclude<NonNullable<AccountOverviewResponse>["total_income_mtd"], null | undefined>, string> = true
// R4
const _a10: AssertEqual<Exclude<NonNullable<AccountOverviewResponse>["total_spend_mtd"], null | undefined>, string> = true
// R5
const _a11: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<ExpenseBreakdownResponse>["items"]>[number]>["amount_kd"], null | undefined>, number> = true
// R5
const _a12: AssertEqual<Exclude<NonNullable<ExpenseBreakdownResponse>["total_kd"], null | undefined>, number> = true
// R6
const _a13: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<ExpenseMerchantTrendResponse>["series"]>[number]>["total_kd"], null | undefined>, number> = true
// R7
const _a14: AssertEqual<Exclude<NonNullable<NonNullable<BudgetMetricsResponse>["avg12_by_category"]>[string], null | undefined>, number> = true
// R7
const _a15: AssertEqual<Exclude<NonNullable<NonNullable<BudgetMetricsResponse>["range_spent_by_category"]>[string], null | undefined>, number> = true
// R7
const _a16: AssertEqual<Exclude<NonNullable<NonNullable<BudgetMetricsResponse>["spent_by_category"]>[string], null | undefined>, number> = true
// R8
const _a17: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["account_overview"]>["manual_entry_summary"]>["spend_mtd"], null | undefined>, string> = true
// R8
const _a18: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["account_overview"]>["month_trend"]>[number]>["income"], null | undefined>, string> = true
// R8
const _a19: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["account_overview"]>["month_trend"]>[number]>["spend"], null | undefined>, string> = true
// R8
const _a20: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["account_overview"]>["top_categories"]>[number]>["amount_kd"], null | undefined>, string> = true
// R8
const _a21: AssertEqual<Exclude<NonNullable<NonNullable<DashboardBundleResponse>["account_overview"]>["total_income_mtd"], null | undefined>, string> = true
// R8
const _a22: AssertEqual<Exclude<NonNullable<NonNullable<DashboardBundleResponse>["account_overview"]>["total_spend_mtd"], null | undefined>, string> = true
// R8
const _a23: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["budget"]>["items"]>[number]>["amount_kd"], null | undefined>, string> = true
// R8
const _a24: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["budget"]>["profile_context"]>["budget_to_income_pct"], null | undefined>, string> = true
// R8
const _a25: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["budget"]>["profile_context"]>["budget_total_kd"], null | undefined>, string> = true
// R8
const _a26: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["budget"]>["profile_context"]>["monthly_income_kd"], null | undefined>, string> = true
// R8
const _a27: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["budget_alerts"]>["items"]>[number]>["budget_kd"], null | undefined>, string> = true
// R8
const _a28: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["budget_alerts"]>["items"]>[number]>["spent_kd"], null | undefined>, string> = true
// R8
const _a29: AssertEqual<Exclude<NonNullable<NonNullable<DashboardBundleResponse>["safe_to_spend"]>["actual_spend_kd"], null | undefined>, string> = true
// R8
const _a30: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<DashboardBundleResponse>["safe_to_spend"]>["committed_breakdown_kd"]>["budget_allocations"], null | undefined>, string> = true
// R8
const _a31: AssertEqual<Exclude<NonNullable<NonNullable<DashboardBundleResponse>["safe_to_spend"]>["committed_kd"], null | undefined>, string> = true
// R8
const _a32: AssertEqual<Exclude<NonNullable<NonNullable<DashboardBundleResponse>["safe_to_spend"]>["daily_rate_kd"], null | undefined>, string> = true
// R8
const _a33: AssertEqual<Exclude<NonNullable<NonNullable<DashboardBundleResponse>["safe_to_spend"]>["monthly_income_kd"], null | undefined>, string> = true
// R8
const _a34: AssertEqual<Exclude<NonNullable<NonNullable<DashboardBundleResponse>["safe_to_spend"]>["remaining_budget_kd"], null | undefined>, string> = true
// R8
const _a35: AssertEqual<Exclude<NonNullable<NonNullable<DashboardBundleResponse>["safe_to_spend"]>["total_budget_kd"], null | undefined>, string> = true
// R9
const _a36: AssertEqual<Exclude<NonNullable<SafeToSpendResponse>["actual_spend_kd"], null | undefined>, string> = true
// R9
const _a37: AssertEqual<Exclude<NonNullable<NonNullable<SafeToSpendResponse>["committed_breakdown_kd"]>["budget_allocations"], null | undefined>, string> = true
// R9
const _a38: AssertEqual<Exclude<NonNullable<SafeToSpendResponse>["committed_kd"], null | undefined>, string> = true
// R9
const _a39: AssertEqual<Exclude<NonNullable<SafeToSpendResponse>["daily_rate_kd"], null | undefined>, string> = true
// R9
const _a40: AssertEqual<Exclude<NonNullable<SafeToSpendResponse>["monthly_income_kd"], null | undefined>, string> = true
// R9
const _a41: AssertEqual<Exclude<NonNullable<SafeToSpendResponse>["remaining_budget_kd"], null | undefined>, string> = true
// R9
const _a42: AssertEqual<Exclude<NonNullable<SafeToSpendResponse>["total_budget_kd"], null | undefined>, string> = true
// R10
const _a43: AssertEqual<Exclude<NonNullable<WeeklyDigestResponse>["last_week_expense_kd"], null | undefined>, string> = true
// R10
const _a44: AssertEqual<Exclude<NonNullable<WeeklyDigestResponse>["safe_to_spend_today_kd"], null | undefined>, string> = true
// R10
const _a45: AssertEqual<Exclude<NonNullable<WeeklyDigestResponse>["this_week_expense_kd"], null | undefined>, string> = true
// R10
const _a46: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<WeeklyDigestResponse>["top_categories"]>[number]>["amount_kd"], null | undefined>, string> = true
// R11
const _a47: AssertEqual<Exclude<NonNullable<IncomePatternResponse>["monthly_income_kd"], null | undefined>, string> = true
// R11
const _a48: AssertEqual<Exclude<NonNullable<IncomePatternResponse>["suggested_monthly_income_kd"], null | undefined>, string> = true
// R12
const _a49: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<RecurringPatternsResponse>["patterns"]>[number]>["avg_amount_kd"], null | undefined>, string> = true
// R13
const _a50: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<SnapshotResponse>["cash_flow"]>["30d"]>["expense_kd"], null | undefined>, string> = true
// R13
const _a51: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<SnapshotResponse>["cash_flow"]>["30d"]>["income_kd"], null | undefined>, string> = true
// R13
const _a52: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<SnapshotResponse>["cash_flow"]>["30d"]>["net_kd"], null | undefined>, string> = true
// R13
const _a53: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<SnapshotResponse>["cash_flow"]>["60d"]>["expense_kd"], null | undefined>, string> = true
// R13
const _a54: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<SnapshotResponse>["cash_flow"]>["60d"]>["income_kd"], null | undefined>, string> = true
// R13
const _a55: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<SnapshotResponse>["cash_flow"]>["60d"]>["net_kd"], null | undefined>, string> = true
// R13
const _a56: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<SnapshotResponse>["cash_flow"]>["90d"]>["expense_kd"], null | undefined>, string> = true
// R13
const _a57: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<SnapshotResponse>["cash_flow"]>["90d"]>["income_kd"], null | undefined>, string> = true
// R13
const _a58: AssertEqual<Exclude<NonNullable<NonNullable<NonNullable<SnapshotResponse>["cash_flow"]>["90d"]>["net_kd"], null | undefined>, string> = true
// R13
const _a59: AssertEqual<Exclude<NonNullable<NonNullable<SnapshotResponse>["net_position"]>["expense_total_kd"], null | undefined>, string> = true
// R13
const _a60: AssertEqual<Exclude<NonNullable<NonNullable<SnapshotResponse>["net_position"]>["income_total_kd"], null | undefined>, string> = true
// R13
const _a61: AssertEqual<Exclude<NonNullable<NonNullable<SnapshotResponse>["net_position"]>["net_kd"], null | undefined>, string> = true
